version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5005:5005"
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: mysql:latest
    #platform: linux/x86_64
    ports:
      - "3305:3305"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
  