version: '3'
services:
  web:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    ports:
      - "2000:2000"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql